<?php
/**
 * Material Symbols Rounded icon family for SiteOrigin / Zen Addons widgets.
 *
 * Registers a "Material Symbols Rounded" icon family with SiteOrigin Widgets
 * Bundle so the glyphs appear in the icon picker of every widget that uses an
 * 'type' => 'icon' field (Counter, Services Grid, Hover Card, etc.) across both
 * the free and Pro Zen Addons widget sets.
 *
 * The font is self-hosted (no Google Fonts / gstatic CDN) for GDPR and
 * WordPress.org guideline compliance. SiteOrigin enqueues the family stylesheet
 * ON DEMAND only when a Material icon is actually rendered, so there is no
 * global font bloat.
 *
 * Credit: Material Symbols is created by Google and distributed under the
 * Apache License 2.0. A curated subset and the full license text are bundled in
 * assets/fonts/.
 *
 * @package ZenAddonsForSiteOrigin
 * @since   1.11.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

/**
 * Register the Material Symbols Rounded family with SiteOrigin.
 *
 * @param array $families Existing icon families keyed by family slug.
 *
 * @return array Families with the 'material-symbols' family appended.
 */
function zaso_material_symbols_icon_family( $families ) {
	// Note: the family slug must not contain a hyphen. SiteOrigin parses an icon
	// value with explode( '-', $value, 2 ), so a hyphenated slug would split into
	// the wrong family/icon parts and the glyph would never render.
	$families['materialsymbols'] = array(
		'name'      => __( 'Material Symbols Rounded', 'zaso' ),
		'style_uri' => ZASO_BASE_DIR . 'assets/css/material-symbols.css?ver=' . ZASO_VERSION,
		'icons'     => zaso_material_symbols_icons(),
	);

	return $families;
}
add_filter( 'siteorigin_widgets_icon_families', 'zaso_material_symbols_icon_family' );

/**
 * The curated Material Symbols Rounded icon map.
 *
 * Each entry maps an icon name to its glyph codepoint as an HTML entity, which
 * SiteOrigin outputs in the span's data-sow-icon attribute and the bundled
 * stylesheet renders via content: attr( data-sow-icon ).
 *
 * @return array<string,string> Icon name => HTML entity codepoint.
 */
function zaso_material_symbols_icons() {
	return array(
		'ac_unit' => '&#xeb3b;',
		'access_time' => '&#xefd6;',
		'accessibility' => '&#xe84e;',
		'accessible' => '&#xe914;',
		'account_balance' => '&#xe84f;',
		'account_balance_wallet' => '&#xe850;',
		'account_circle' => '&#xf20b;',
		'add' => '&#xe145;',
		'add_circle' => '&#xe990;',
		'add_shopping_cart' => '&#xe854;',
		'admin_panel_settings' => '&#xef3d;',
		'agriculture' => '&#xea79;',
		'air' => '&#xefd8;',
		'alarm' => '&#xe855;',
		'analytics' => '&#xef3e;',
		'apartment' => '&#xea40;',
		'api' => '&#xf1b7;',
		'apps' => '&#xe5c3;',
		'arrow_back' => '&#xe5c4;',
		'arrow_back_ios' => '&#xe5e0;',
		'arrow_downward' => '&#xe5db;',
		'arrow_drop_down' => '&#xe5c5;',
		'arrow_drop_up' => '&#xe5c7;',
		'arrow_forward' => '&#xe5c8;',
		'arrow_forward_ios' => '&#xe5e1;',
		'arrow_left' => '&#xe5de;',
		'arrow_right' => '&#xe5df;',
		'arrow_upward' => '&#xe5d8;',
		'article' => '&#xef87;',
		'aspect_ratio' => '&#xe85b;',
		'assessment' => '&#xf0cc;',
		'assignment' => '&#xe85d;',
		'assignment_turned_in' => '&#xe862;',
		'attach_file' => '&#xe226;',
		'attach_money' => '&#xe227;',
		'attachment' => '&#xe2bc;',
		'auto_awesome' => '&#xe65f;',
		'auto_stories' => '&#xe666;',
		'autorenew' => '&#xe863;',
		'backup' => '&#xe864;',
		'bar_chart' => '&#xe26b;',
		'barcode' => '&#xe70b;',
		'battery_charging_full' => '&#xe1a3;',
		'battery_full' => '&#xe1a5;',
		'beach_access' => '&#xeb3e;',
		'biotech' => '&#xea3a;',
		'bloodtype' => '&#xefe4;',
		'bluetooth' => '&#xe1a7;',
		'bluetooth_disabled' => '&#xe1a9;',
		'bolt' => '&#xea0b;',
		'book' => '&#xe86e;',
		'bookmark' => '&#xe8e7;',
		'bookmark_border' => '&#xe8e7;',
		'brightness_high' => '&#xe1ac;',
		'brightness_low' => '&#xe1ad;',
		'brush' => '&#xe3ae;',
		'bug_report' => '&#xe868;',
		'build' => '&#xf8cd;',
		'business' => '&#xe7ee;',
		'business_center' => '&#xeb3f;',
		'cached' => '&#xe86a;',
		'cake' => '&#xe7e9;',
		'calculate' => '&#xea5f;',
		'calendar_month' => '&#xebcc;',
		'calendar_today' => '&#xe935;',
		'call' => '&#xf0d4;',
		'camera' => '&#xe3af;',
		'camera_alt' => '&#xe412;',
		'campaign' => '&#xef49;',
		'cancel' => '&#xe888;',
		'card_giftcard' => '&#xe8f6;',
		'carpenter' => '&#xf1f8;',
		'cast' => '&#xe307;',
		'cast_connected' => '&#xe308;',
		'category' => '&#xe72c;',
		'celebration' => '&#xea65;',
		'chat' => '&#xe0c9;',
		'chat_bubble' => '&#xe0cb;',
		'chat_bubble_outline' => '&#xe0cb;',
		'check' => '&#xe668;',
		'check_circle' => '&#xf0be;',
		'checklist' => '&#xe6b1;',
		'chevron_left' => '&#xe5cb;',
		'chevron_right' => '&#xe5cc;',
		'child_care' => '&#xeb41;',
		'close' => '&#xe5cd;',
		'cloud' => '&#xf15c;',
		'cloud_done' => '&#xe2bf;',
		'cloud_download' => '&#xe2c0;',
		'cloud_off' => '&#xe2c1;',
		'cloud_upload' => '&#xe2c3;',
		'code' => '&#xe86f;',
		'collections' => '&#xe3d3;',
		'color_lens' => '&#xe40a;',
		'colorize' => '&#xe3b8;',
		'comment' => '&#xe24c;',
		'compost' => '&#xe761;',
		'computer' => '&#xe31e;',
		'construction' => '&#xea3c;',
		'content_copy' => '&#xe14d;',
		'content_cut' => '&#xe14e;',
		'content_paste' => '&#xe14f;',
		'contrast' => '&#xeb37;',
		'corporate_fare' => '&#xf1d0;',
		'create' => '&#xf097;',
		'create_new_folder' => '&#xe2cc;',
		'credit_card' => '&#xe8a1;',
		'crop' => '&#xe3be;',
		'crop_free' => '&#xe3c2;',
		'cruelty_free' => '&#xe799;',
		'css' => '&#xeb93;',
		'currency_bitcoin' => '&#xebc5;',
		'dark_mode' => '&#xe51c;',
		'dashboard' => '&#xe871;',
		'data_array' => '&#xead1;',
		'data_object' => '&#xead3;',
		'database' => '&#xf20e;',
		'date_range' => '&#xe916;',
		'delete' => '&#xe92e;',
		'delete_forever' => '&#xe92b;',
		'description' => '&#xe873;',
		'desktop_windows' => '&#xe30c;',
		'developer_mode' => '&#xf2e2;',
		'diamond' => '&#xead5;',
		'directions' => '&#xe52e;',
		'directions_bike' => '&#xe52f;',
		'directions_bus' => '&#xeff6;',
		'directions_car' => '&#xeff7;',
		'directions_walk' => '&#xe536;',
		'diversity_3' => '&#xf8d9;',
		'dns' => '&#xe875;',
		'domain' => '&#xe7ee;',
		'done' => '&#xe876;',
		'done_all' => '&#xe877;',
		'download' => '&#xf090;',
		'drafts' => '&#xe151;',
		'drive_file_move' => '&#xe9a1;',
		'east' => '&#xf1df;',
		'eco' => '&#xea35;',
		'edit' => '&#xf097;',
		'edit_note' => '&#xe745;',
		'elderly' => '&#xf21a;',
		'email' => '&#xe159;',
		'emoji_events' => '&#xea23;',
		'emoji_objects' => '&#xea24;',
		'engineering' => '&#xea3d;',
		'enhanced_encryption' => '&#xe63f;',
		'equalizer' => '&#xe01d;',
		'error' => '&#xf8b6;',
		'error_outline' => '&#xf8b6;',
		'event' => '&#xe878;',
		'expand_less' => '&#xe5ce;',
		'expand_more' => '&#xe5cf;',
		'explore' => '&#xe87a;',
		'extension' => '&#xe87b;',
		'face' => '&#xf008;',
		'fact_check' => '&#xf0c5;',
		'fast_forward' => '&#xe01f;',
		'fast_rewind' => '&#xe020;',
		'fastfood' => '&#xe57a;',
		'favorite' => '&#xe87e;',
		'favorite_border' => '&#xe87e;',
		'fax' => '&#xead8;',
		'file_download' => '&#xf090;',
		'file_upload' => '&#xf09b;',
		'filter' => '&#xe3d3;',
		'filter_alt' => '&#xef4f;',
		'filter_list' => '&#xe152;',
		'fingerprint' => '&#xe90d;',
		'first_page' => '&#xe5dc;',
		'fitness_center' => '&#xeb43;',
		'flag' => '&#xf0c6;',
		'flag_circle' => '&#xeaf8;',
		'flash_off' => '&#xe3e6;',
		'flash_on' => '&#xe3e7;',
		'flight' => '&#xe539;',
		'folder' => '&#xe2c7;',
		'folder_open' => '&#xe2c8;',
		'forest' => '&#xea99;',
		'format_align_center' => '&#xe234;',
		'format_align_left' => '&#xe236;',
		'format_align_right' => '&#xe237;',
		'format_bold' => '&#xe238;',
		'format_italic' => '&#xe23f;',
		'format_list_bulleted' => '&#xe241;',
		'format_list_numbered' => '&#xe242;',
		'format_paint' => '&#xe243;',
		'format_quote' => '&#xe244;',
		'format_underlined' => '&#xe249;',
		'forum' => '&#xe8af;',
		'forward' => '&#xf57a;',
		'fullscreen' => '&#xe5d0;',
		'fullscreen_exit' => '&#xe5d1;',
		'functions' => '&#xe24a;',
		'g_translate' => '&#xe927;',
		'gpp_good' => '&#xf013;',
		'grade' => '&#xf09a;',
		'gradient' => '&#xe3e9;',
		'grass' => '&#xf205;',
		'grid_view' => '&#xe9b0;',
		'group' => '&#xea21;',
		'groups' => '&#xf233;',
		'handshake' => '&#xebcb;',
		'handyman' => '&#xf10b;',
		'hardware' => '&#xea59;',
		'headphones' => '&#xf01f;',
		'healing' => '&#xe3f3;',
		'health_and_safety' => '&#xe1d5;',
		'help' => '&#xe8fd;',
		'help_outline' => '&#xe8fd;',
		'history' => '&#xe8b3;',
		'home' => '&#xe9b2;',
		'hourglass_empty' => '&#xe88b;',
		'hourglass_full' => '&#xe88c;',
		'house' => '&#xea44;',
		'html' => '&#xeb7e;',
		'http' => '&#xe902;',
		'https' => '&#xe899;',
		'icecream' => '&#xea69;',
		'image' => '&#xe3f4;',
		'image_search' => '&#xe43f;',
		'import_contacts' => '&#xe0e0;',
		'inbox' => '&#xe156;',
		'info' => '&#xe88e;',
		'insert_drive_file' => '&#xe674;',
		'insights' => '&#xf092;',
		'integration_instructions' => '&#xef54;',
		'javascript' => '&#xeb7c;',
		'key' => '&#xe73c;',
		'keyboard' => '&#xe312;',
		'language' => '&#xea07;',
		'laptop' => '&#xe31e;',
		'last_page' => '&#xe5dd;',
		'launch' => '&#xe89e;',
		'leaderboard' => '&#xf20c;',
		'library_books' => '&#xe02f;',
		'library_music' => '&#xe030;',
		'light_mode' => '&#xe518;',
		'lightbulb' => '&#xe90f;',
		'lightbulb_outline' => '&#xe90f;',
		'link' => '&#xe250;',
		'local_bar' => '&#xe540;',
		'local_cafe' => '&#xeb44;',
		'local_dining' => '&#xe561;',
		'local_hospital' => '&#xe548;',
		'local_library' => '&#xe54b;',
		'local_mall' => '&#xe54c;',
		'local_offer' => '&#xf05b;',
		'local_shipping' => '&#xe558;',
		'local_taxi' => '&#xe559;',
		'location_off' => '&#xe0c7;',
		'location_on' => '&#xf1db;',
		'lock' => '&#xe899;',
		'lock_open' => '&#xe898;',
		'lock_outline' => '&#xe899;',
		'lock_reset' => '&#xeade;',
		'lunch_dining' => '&#xea61;',
		'mail' => '&#xe159;',
		'mail_outline' => '&#xe159;',
		'manage_accounts' => '&#xf02e;',
		'map' => '&#xe55b;',
		'markunread' => '&#xe159;',
		'medical_services' => '&#xf109;',
		'medication' => '&#xf033;',
		'memory' => '&#xe322;',
		'menu' => '&#xe5d2;',
		'menu_book' => '&#xea19;',
		'message' => '&#xe0c9;',
		'mic' => '&#xe31d;',
		'mic_off' => '&#xe02b;',
		'military_tech' => '&#xea3f;',
		'monetization_on' => '&#xe263;',
		'money' => '&#xe57d;',
		'monitor_heart' => '&#xeaa2;',
		'mood' => '&#xea22;',
		'more_horiz' => '&#xe5d3;',
		'more_vert' => '&#xe5d4;',
		'mouse' => '&#xe323;',
		'movie' => '&#xe684;',
		'music_note' => '&#xe405;',
		'my_location' => '&#xe55c;',
		'navigation' => '&#xe55d;',
		'near_me' => '&#xe569;',
		'network_check' => '&#xe640;',
		'new_releases' => '&#xef76;',
		'nightlight' => '&#xf03d;',
		'no_encryption' => '&#xf03f;',
		'north' => '&#xf1e0;',
		'north_east' => '&#xf1e1;',
		'north_west' => '&#xf1e2;',
		'note' => '&#xe674;',
		'notifications' => '&#xe7f5;',
		'notifications_active' => '&#xe7f7;',
		'notifications_none' => '&#xe7f5;',
		'notifications_off' => '&#xe7f6;',
		'open_in_full' => '&#xf1ce;',
		'open_in_new' => '&#xe89e;',
		'palette' => '&#xe40a;',
		'park' => '&#xea63;',
		'password' => '&#xf042;',
		'pause' => '&#xe034;',
		'pause_circle' => '&#xe1a2;',
		'payment' => '&#xe8a1;',
		'payments' => '&#xef63;',
		'pedal_bike' => '&#xeb29;',
		'pending' => '&#xef64;',
		'pending_actions' => '&#xf1bb;',
		'people' => '&#xea21;',
		'person' => '&#xf0d3;',
		'person_add' => '&#xea4d;',
		'person_remove' => '&#xef66;',
		'pets' => '&#xe91d;',
		'phone' => '&#xf0d4;',
		'phone_android' => '&#xf2db;',
		'phone_in_talk' => '&#xe61d;',
		'phone_iphone' => '&#xf2da;',
		'photo' => '&#xe693;',
		'photo_camera' => '&#xe412;',
		'php' => '&#xeb8f;',
		'picture_as_pdf' => '&#xe415;',
		'pie_chart' => '&#xf0da;',
		'place' => '&#xf1db;',
		'play_arrow' => '&#xe037;',
		'play_circle' => '&#xe1c4;',
		'playlist_add' => '&#xe03b;',
		'playlist_add_check' => '&#xe065;',
		'playlist_play' => '&#xe05f;',
		'plumbing' => '&#xf107;',
		'policy' => '&#xea17;',
		'pool' => '&#xeb48;',
		'power' => '&#xe63c;',
		'power_off' => '&#xe646;',
		'pregnant_woman' => '&#xf5f1;',
		'price_change' => '&#xf04a;',
		'price_check' => '&#xf04b;',
		'print' => '&#xe8ad;',
		'priority_high' => '&#xe645;',
		'privacy_tip' => '&#xf0dc;',
		'psychology' => '&#xea4a;',
		'public' => '&#xe80b;',
		'qr_code' => '&#xef6b;',
		'qr_code_2' => '&#xe00a;',
		'qr_code_scanner' => '&#xf206;',
		'query_stats' => '&#xe4fc;',
		'question_answer' => '&#xe8af;',
		'queue_music' => '&#xe03d;',
		'ramen_dining' => '&#xea64;',
		'receipt' => '&#xe8b0;',
		'receipt_long' => '&#xef6e;',
		'recycling' => '&#xe760;',
		'redeem' => '&#xe8f6;',
		'redo' => '&#xe15a;',
		'refresh' => '&#xe5d5;',
		'remove' => '&#xe15b;',
		'remove_circle' => '&#xf08f;',
		'remove_shopping_cart' => '&#xe928;',
		'repeat' => '&#xe040;',
		'replay' => '&#xe042;',
		'reply' => '&#xe15e;',
		'report' => '&#xf052;',
		'report_problem' => '&#xf083;',
		'request_quote' => '&#xf1b6;',
		'restaurant' => '&#xe56c;',
		'restore' => '&#xe8b3;',
		'rocket' => '&#xeba5;',
		'rocket_launch' => '&#xeb9b;',
		'router' => '&#xe328;',
		'rule' => '&#xf1c2;',
		'save' => '&#xe161;',
		'save_alt' => '&#xf090;',
		'savings' => '&#xe2eb;',
		'scanner' => '&#xe329;',
		'schedule' => '&#xefd6;',
		'school' => '&#xe80c;',
		'science' => '&#xea4b;',
		'screen_share' => '&#xe0e2;',
		'sd_card' => '&#xe623;',
		'search' => '&#xef7a;',
		'security' => '&#xe32a;',
		'sell' => '&#xf05b;',
		'send' => '&#xe163;',
		'sentiment_satisfied' => '&#xe813;',
		'settings' => '&#xe8b8;',
		'severe_cold' => '&#xebd3;',
		'share' => '&#xe80d;',
		'shield' => '&#xe9e0;',
		'shopping_bag' => '&#xf1cc;',
		'shopping_basket' => '&#xe8cb;',
		'shopping_cart' => '&#xe8cc;',
		'show_chart' => '&#xe6e1;',
		'shuffle' => '&#xe043;',
		'signal_cellular_alt' => '&#xe202;',
		'skip_next' => '&#xe044;',
		'skip_previous' => '&#xe045;',
		'smart_toy' => '&#xf06c;',
		'sms' => '&#xe625;',
		'snippet_folder' => '&#xf1c7;',
		'sort' => '&#xe164;',
		'south' => '&#xf1e3;',
		'south_east' => '&#xf1e4;',
		'south_west' => '&#xf1e5;',
		'spa' => '&#xeb4c;',
		'speaker' => '&#xe32d;',
		'speaker_group' => '&#xe32e;',
		'spellcheck' => '&#xe8ce;',
		'sports_esports' => '&#xea28;',
		'star' => '&#xf09a;',
		'star_border' => '&#xf09a;',
		'star_half' => '&#xe839;',
		'stop' => '&#xe047;',
		'stop_circle' => '&#xef71;',
		'stop_screen_share' => '&#xe0e3;',
		'storage' => '&#xe1db;',
		'store' => '&#xe8d1;',
		'storefront' => '&#xea12;',
		'supervisor_account' => '&#xe8d3;',
		'swap_horiz' => '&#xe8d4;',
		'swap_vert' => '&#xe8d5;',
		'system_update' => '&#xf2cd;',
		'sync' => '&#xe627;',
		'table_chart' => '&#xe265;',
		'table_rows' => '&#xf101;',
		'tablet' => '&#xe32f;',
		'tablet_mac' => '&#xe331;',
		'task' => '&#xf075;',
		'task_alt' => '&#xe2e6;',
		'terminal' => '&#xeb8e;',
		'text_fields' => '&#xe262;',
		'text_snippet' => '&#xf1c6;',
		'thermostat' => '&#xf076;',
		'thumb_down' => '&#xf578;',
		'thumb_up' => '&#xf577;',
		'timeline' => '&#xe922;',
		'timer' => '&#xe425;',
		'tips_and_updates' => '&#xe79a;',
		'title' => '&#xe264;',
		'today' => '&#xe8df;',
		'token' => '&#xea25;',
		'topic' => '&#xf1c8;',
		'tour' => '&#xef75;',
		'toys' => '&#xe332;',
		'train' => '&#xe570;',
		'translate' => '&#xe8e2;',
		'trending_down' => '&#xe8e3;',
		'trending_flat' => '&#xe8e4;',
		'trending_up' => '&#xe8e5;',
		'tune' => '&#xe429;',
		'tv' => '&#xe63b;',
		'two_wheeler' => '&#xe9f9;',
		'umbrella' => '&#xf1ad;',
		'undo' => '&#xe166;',
		'unfold_less' => '&#xe5d6;',
		'unfold_more' => '&#xe5d7;',
		'update' => '&#xe923;',
		'upload' => '&#xf09b;',
		'usb' => '&#xe1e0;',
		'vaccines' => '&#xe138;',
		'verified' => '&#xef76;',
		'verified_user' => '&#xf013;',
		'videocam' => '&#xe04b;',
		'videocam_off' => '&#xe04c;',
		'view_column' => '&#xe8ec;',
		'view_list' => '&#xe8ef;',
		'view_module' => '&#xe8f0;',
		'view_quilt' => '&#xe8f1;',
		'visibility' => '&#xe8f4;',
		'visibility_lock' => '&#xf653;',
		'visibility_off' => '&#xe8f5;',
		'volume_down' => '&#xe04d;',
		'volume_mute' => '&#xe04e;',
		'volume_off' => '&#xe04f;',
		'volume_up' => '&#xe050;',
		'volunteer_activism' => '&#xea70;',
		'vpn_key' => '&#xe0da;',
		'vpn_lock' => '&#xe62f;',
		'wallet' => '&#xf8ff;',
		'warning' => '&#xf083;',
		'watch' => '&#xe334;',
		'watch_later' => '&#xefd6;',
		'water_drop' => '&#xe798;',
		'wb_cloudy' => '&#xf15c;',
		'wb_sunny' => '&#xe430;',
		'webhook' => '&#xeb92;',
		'west' => '&#xf1e6;',
		'wheelchair_pickup' => '&#xf1ab;',
		'widgets' => '&#xe1bd;',
		'wifi' => '&#xe63e;',
		'wifi_off' => '&#xe648;',
		'work' => '&#xe943;',
		'work_outline' => '&#xe943;',
		'workspace_premium' => '&#xe7af;',
		'yard' => '&#xf089;',
		'zoom_in' => '&#xe8ff;',
		'zoom_out' => '&#xe900;',
	);
}
